language: cpp

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - gcc-5
    - g++-5
    - gcc-7
    - g++-7
    - clang-3.9
    - cmake
    - cmake-data
    - libboost-all-dev

matrix:
  include:
    - compiler: gcc-5
      env: MATRIX_EVAL="CC=gcc-5 CXX=g++-5"
    - compiler: gcc-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - compiler: clang-3.9
      env: MATRIX_EVAL="CC=clang-3.9 CXX=clang++-3.9"

before_install:
- eval "${MATRIX_EVAL}"

before_script:
- cmake . -DMCRL2_ENABLE_GUI_TOOLS=OFF -DMCRL2_ENABLE_EXPERIMENTAL=ON

script:
- make
#- ctest -E "random|headertest" --output-on-failure

